# Generated by Django 2.2.1 on 2019-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=7)),
                ('pet', models.PositiveSmallIntegerField(choices=[(1, 'Cats'), (2, 'Dogs')], default=1)),
            ],
        ),
    ]
